# Generated by Django 3.1.1 on 2020-09-12 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='readers',
            fields=[
                ('username', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
    ]
