# Generated by Django 3.1.1 on 2020-09-12 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_auth', '0003_story_to_read'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='story_to_read',
            new_name='story',
        ),
    ]
