# Generated by Django 3.1.1 on 2020-09-13 08:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_auth', '0004_auto_20200912_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='total_read',
        ),
        migrations.AddField(
            model_name='story',
            name='total_read',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
