# Generated by Django 3.1.1 on 2020-09-13 10:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_auth', '0006_auto_20200913_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='total_read',
            field=models.ManyToManyField(blank=True, related_name='total_reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
