# Generated by Django 3.1.1 on 2020-09-13 11:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_auth', '0007_auto_20200913_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='current_view',
        ),
        migrations.AddField(
            model_name='story',
            name='current_view',
            field=models.ManyToManyField(blank=True, related_name='current_reads', to=settings.AUTH_USER_MODEL),
        ),
    ]
