# Generated by Django 3.1.1 on 2020-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='story_to_read',
            fields=[
                ('story_id', models.IntegerField(primary_key=True, serialize=False)),
                ('story_name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('current_view', models.IntegerField(default=0)),
                ('total_read', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Story section',
                'verbose_name_plural': 'Stories',
            },
        ),
    ]
