# Generated by Django 3.1.1 on 2020-09-12 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='story_to_read',
        ),
    ]
